# Generated by Django 3.2.19 on 2023-09-28 08:39

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0011_2_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancetransaction',
            name='included_in_payout',
            field=djstripe.fields.StripeForeignKey(blank=True, help_text='The payout object to which this Balance Transaction is related', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='included_balance_transactions', to='djstripe.payout', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD),
        ),
    ]
