# Generated by Django 3.2.19 on 2023-12-05 10:16

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0013_customer_cash_balance'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(django.db.models.expressions.F('metadata__userUid'), name='metadata__userUid_idx'),
        ),
    ]
