# Generated by Django 3.2.19 on 2023-12-12 11:36

from django.db import migrations, models
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0014_customer_metadata__useruid_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(blank=True, db_index=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='session',
            name='payment_method_types',
            field=djstripe.fields.JSONField(db_index=True),
        ),
    ]
