# Generated by Django 3.2.19 on 2024-11-11 12:55

from django.db import migrations
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0015_auto_20231212_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=djstripe.fields.StripeEnumField(blank=True, enum=djstripe.enums.RefundStatus, max_length=15),
        ),
    ]
