# Generated by Django 3.2.19 on 2026-06-24 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0016_alter_refund_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCashBalanceTransaction',
            fields=[
                ('djstripe_created', models.DateTimeField(auto_now_add=True)),
                ('djstripe_updated', models.DateTimeField(auto_now=True)),
                ('djstripe_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('id', djstripe.fields.StripeIdField(max_length=255, unique=True)),
                ('livemode', models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True)),
                ('created', djstripe.fields.StripeDateTimeField(blank=True, null=True)),
                ('metadata', djstripe.fields.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='A description of this object.', null=True)),
                ('currency', djstripe.fields.StripeCurrencyCodeField(max_length=3)),
                ('ending_balance', djstripe.fields.StripeQuantumCurrencyAmountField()),
                ('funded', djstripe.fields.JSONField(blank=True, null=True)),
                ('net_amount', djstripe.fields.StripeQuantumCurrencyAmountField()),
                ('type', djstripe.fields.StripeEnumField(enum=djstripe.enums.CustomerCashBalanceTransactionType, max_length=22)),
                ('adjusted_for_overdraft_balance_transaction', djstripe.fields.StripeForeignKey(blank=True, help_text='The BalanceTransaction that corresponds to funds taken out of your Stripe balance, if `type=adjusted_for_overdraft`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_balance_transactions_overdraft', to='djstripe.balancetransaction', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
                ('adjusted_for_overdraft_linked_transaction', djstripe.fields.StripeForeignKey(blank=True, help_text='The Cash Balance Transaction that brought the customer balance negative, triggering the clawback of funds, if `type=adjusted_for_overdraft`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overdraft_adjustments', to='djstripe.customercashbalancetransaction', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
                ('applied_to_payment_payment_intent', djstripe.fields.StripeForeignKey(blank=True, help_text='The PaymentIntent that funds were applied to, if `type=applied_to_payment`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_balance_transactions', to='djstripe.paymentintent', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
                ('customer', djstripe.fields.StripeForeignKey(help_text='The customer whose available cash balance changed as a result of this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='cash_balance_transactions', to='djstripe.customer', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
                ('djstripe_owner_account', djstripe.fields.StripeForeignKey(blank=True, help_text='The Stripe Account this object belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
                ('refunded_from_payment_refund', djstripe.fields.StripeForeignKey(blank=True, help_text="The Refund that moved these funds into the customer's cash balance, if `type=refunded_from_payment`.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_balance_transactions', to='djstripe.refund', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
                ('transferred_to_balance_balance_transaction', djstripe.fields.StripeForeignKey(blank=True, help_text='The BalanceTransaction that corresponds to funds transferred to your Stripe balance, if `type=transferred_to_balance`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_balance_transactions', to='djstripe.balancetransaction', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
                ('unapplied_from_payment_payment_intent', djstripe.fields.StripeForeignKey(blank=True, help_text='The PaymentIntent that funds were unapplied from, if `type=unapplied_from_payment`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_balance_transactions_unapplied', to='djstripe.paymentintent', to_field=settings.DJSTRIPE_FOREIGN_KEY_TO_FIELD)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
