# Generated by Django 3.2.19 on 2026-09-08 13:20

from django.db import migrations
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0017_customercashbalancetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='reporting_category',
            field=djstripe.fields.StripeEnumField(enum=djstripe.enums.BalanceTransactionReportingCategory, max_length=30),
        ),
    ]
